"""
OceanPulse Maritime Port & Fleet Infrastructure Matrix
Covers 7 East Coast Indian Ports and 5 Global Origin Hubs with exact physical constraints.
"""

EAST_COAST_PORT_MATRIX = {
    "Paradip": {
        "key": "Paradip",
        "name": "Paradip Port (Odisha)",
        "state": "Odisha",
        "maxDraft": 14.5,
        "maxLOA": 260,
        "maxBeam": 40.0,
        "allowedClasses": ["Panamax", "Kamsarmax", "Supramax", "Ultramax", "Handysize"],
        "dailyDischargeRate": 45000,
        "portTariffPerTon": 3.80,
        "demurrageRatePerDay": 22000,
        "avgWaitingDays": 3.4,
        "tidalRestriction": "Semi-diurnal; berthing subject to high tide for >14m draft",
        "congestionLevel": "MODERATE",
        "cargoTypes": ["Thermal Coal", "Coking Coal", "Iron Ore Pellets", "Limestone"]
    },
    "Vizag": {
        "key": "Vizag",
        "name": "Visakhapatnam Port (Andhra Pradesh)",
        "state": "Andhra Pradesh",
        "maxDraft": 16.5,
        "maxLOA": 290,
        "maxBeam": 45.0,
        "allowedClasses": ["Capesize", "Kamsarmax", "Panamax", "Ultramax", "Supramax", "Handysize"],
        "dailyDischargeRate": 55000,
        "portTariffPerTon": 4.10,
        "demurrageRatePerDay": 24000,
        "avgWaitingDays": 2.1,
        "tidalRestriction": "Inner harbour 14.5m / Outer harbour up to 18.1m with cape berths",
        "congestionLevel": "LOW",
        "cargoTypes": ["Coking Coal", "Thermal Coal", "Bauxite", "Manganese Ore"]
    },
    "Gangavaram": {
        "key": "Gangavaram",
        "name": "Gangavaram Port (Andhra Pradesh)",
        "state": "Andhra Pradesh",
        "maxDraft": 18.5,
        "maxLOA": 325,
        "maxBeam": 50.0,
        "allowedClasses": ["Newcastlemax", "Capesize", "Kamsarmax", "Panamax", "Supramax", "Handysize"],
        "dailyDischargeRate": 70000,
        "portTariffPerTon": 4.40,
        "demurrageRatePerDay": 28000,
        "avgWaitingDays": 1.6,
        "tidalRestriction": "Deep water all-weather port, minimal tidal dependency",
        "congestionLevel": "LOW",
        "cargoTypes": ["Coking Coal", "Thermal Coal", "Iron Ore", "Limestone"]
    },
    "Gopalpur": {
        "key": "Gopalpur",
        "name": "Gopalpur Port (Odisha)",
        "state": "Odisha",
        "maxDraft": 13.0,
        "maxLOA": 225,
        "maxBeam": 32.5,
        "allowedClasses": ["Supramax", "Ultramax", "Handysize"],
        "dailyDischargeRate": 28000,
        "portTariffPerTon": 3.60,
        "demurrageRatePerDay": 18000,
        "avgWaitingDays": 2.3,
        "tidalRestriction": "Draft limited; seasonal swell during SW monsoon",
        "congestionLevel": "LOW",
        "cargoTypes": ["Thermal Coal", "Limestone", "Ilmenite Sand", "Fertilizer"]
    },
    "Dhamra": {
        "key": "Dhamra",
        "name": "Dhamra Port (Odisha)",
        "state": "Odisha",
        "maxDraft": 17.5,
        "maxLOA": 310,
        "maxBeam": 48.0,
        "allowedClasses": ["Capesize", "Kamsarmax", "Panamax", "Ultramax", "Supramax", "Handysize"],
        "dailyDischargeRate": 65000,
        "portTariffPerTon": 4.50,
        "demurrageRatePerDay": 26000,
        "avgWaitingDays": 2.5,
        "tidalRestriction": "Deep water port with dedicated capesize berths; high-speed conveyors",
        "congestionLevel": "MODERATE",
        "cargoTypes": ["Thermal Coal", "Coking Coal", "Iron Ore", "Limestone"]
    },
    "SagarSandheads": {
        "key": "SagarSandheads",
        "name": "Sagar - Sandheads Anchorage (WB)",
        "state": "West Bengal",
        "maxDraft": 16.0,
        "maxLOA": 300,
        "maxBeam": 46.0,
        "allowedClasses": ["Capesize", "Panamax", "Kamsarmax", "Supramax", "Ultramax"],
        "dailyDischargeRate": 35000,
        "portTariffPerTon": 2.90,
        "demurrageRatePerDay": 20000,
        "avgWaitingDays": 3.0,
        "tidalRestriction": "Open sea lightering point; sea state swell sensitive during monsoon",
        "congestionLevel": "MODERATE",
        "cargoTypes": ["Thermal Coal", "Coking Coal", "Lightering for Haldia & Kolkata"],
        "isLighteringHub": True
    },
    "Haldia": {
        "key": "Haldia",
        "name": "Haldia Dock Complex (West Bengal)",
        "state": "West Bengal",
        "maxDraft": 8.5,
        "maxLOA": 195,
        "maxBeam": 32.2,
        "allowedClasses": ["Handysize", "Supramax (Lightered)"],
        "dailyDischargeRate": 22000,
        "portTariffPerTon": 5.40,
        "demurrageRatePerDay": 16000,
        "avgWaitingDays": 5.2,
        "tidalRestriction": "Severe Hugli river draft constraints; requires lightering at Sandheads for parcels >25k MT",
        "congestionLevel": "HIGH",
        "cargoTypes": ["Coking Coal", "Thermal Coal", "Petcoke", "Manganese Ore"]
    }
}

ORIGIN_PORTS_MATRIX = {
    "Australia_Newcastle": {
        "key": "Australia_Newcastle",
        "name": "Port of Newcastle (PWCS / NCIG)",
        "country": "Australia",
        "region": "Oceania",
        "maxDraft": 15.2,
        "maxLOA": 300,
        "allowedClasses": ["Capesize", "Newcastlemax", "Kamsarmax", "Panamax", "Supramax"],
        "dailyLoadingRate": 85000,
        "portTariffPerTon": 2.20,
        "primaryCommodity": "Thermal & Coking Coal",
        "fobBenchmarkPriceUSD": 139.75,
        "caloricValueKcal": 6000,
        "chokepoints": ["Torres Strait / Great Barrier Reef or Lombok Strait"]
    },
    "Australia_HayPoint": {
        "key": "Australia_HayPoint",
        "name": "Hay Point / Dalrymple Bay (DBCT)",
        "country": "Australia",
        "region": "Oceania",
        "maxDraft": 19.5,
        "maxLOA": 330,
        "allowedClasses": ["Newcastlemax", "Capesize", "Kamsarmax", "Panamax"],
        "dailyLoadingRate": 110000,
        "portTariffPerTon": 2.40,
        "primaryCommodity": "Premium Metallurgical / Coking Coal",
        "fobBenchmarkPriceUSD": 235.00,
        "caloricValueKcal": 6700,
        "chokepoints": ["Hydrographers Passage / Sunda or Lombok Strait"]
    },
    "Indonesia_Samarinda": {
        "key": "Indonesia_Samarinda",
        "name": "Samarinda / Muara Berau Anchorage",
        "country": "Indonesia",
        "region": "East Kalimantan",
        "maxDraft": 18.0,
        "maxLOA": 310,
        "allowedClasses": ["Capesize", "Kamsarmax", "Panamax", "Ultramax", "Supramax", "Handysize"],
        "dailyLoadingRate": 40000,
        "portTariffPerTon": 1.80,
        "primaryCommodity": "Low/Mid CV Thermal Coal (GAR 4200)",
        "fobBenchmarkPriceUSD": 58.70,
        "caloricValueKcal": 4200,
        "chokepoints": ["Makassar Strait / Singapore & Malacca Strait"]
    },
    "Indonesia_Taboneo": {
        "key": "Indonesia_Taboneo",
        "name": "Taboneo Anchorage (Banjarmasin)",
        "country": "Indonesia",
        "region": "South Kalimantan",
        "maxDraft": 17.5,
        "maxLOA": 300,
        "allowedClasses": ["Capesize", "Kamsarmax", "Panamax", "Ultramax", "Supramax"],
        "dailyLoadingRate": 45000,
        "portTariffPerTon": 1.70,
        "primaryCommodity": "Thermal Coal (GAR 4800)",
        "fobBenchmarkPriceUSD": 68.00,
        "caloricValueKcal": 4800,
        "chokepoints": ["Java Sea / Sunda Strait or Malacca"]
    },
    "US_Norfolk": {
        "key": "US_Norfolk",
        "name": "Norfolk Hampton Roads (Pier 6 / Lamberts Pt)",
        "country": "United States",
        "region": "US East Coast",
        "maxDraft": 15.5,
        "maxLOA": 305,
        "allowedClasses": ["Capesize", "Kamsarmax", "Panamax"],
        "dailyLoadingRate": 65000,
        "portTariffPerTon": 3.50,
        "primaryCommodity": "High-Vol & Low-Vol Coking Coal",
        "fobBenchmarkPriceUSD": 220.00,
        "caloricValueKcal": 6800,
        "chokepoints": ["North Atlantic / Cape of Good Hope or Suez Canal"]
    },
    "Mozambique_Maputo": {
        "key": "Mozambique_Maputo",
        "name": "Port of Maputo (Matola TCM)",
        "country": "Mozambique",
        "region": "East Africa",
        "maxDraft": 14.3,
        "maxLOA": 260,
        "allowedClasses": ["Panamax", "Kamsarmax", "Supramax", "Ultramax", "Handysize"],
        "dailyLoadingRate": 35000,
        "portTariffPerTon": 2.80,
        "primaryCommodity": "Thermal & Metallurgical Coal",
        "fobBenchmarkPriceUSD": 94.00,
        "caloricValueKcal": 5500,
        "chokepoints": ["Mozambique Channel / Indian Ocean"]
    },
    "Mozambique_Nacala": {
        "key": "Mozambique_Nacala",
        "name": "Port of Nacala-a-Velha",
        "country": "Mozambique",
        "region": "East Africa",
        "maxDraft": 20.0,
        "maxLOA": 340,
        "allowedClasses": ["Capesize", "Newcastlemax", "Kamsarmax", "Panamax"],
        "dailyLoadingRate": 75000,
        "portTariffPerTon": 2.60,
        "primaryCommodity": "Moatize Coking & Thermal Coal",
        "fobBenchmarkPriceUSD": 165.00,
        "caloricValueKcal": 6200,
        "chokepoints": ["Indian Ocean direct passage"]
    },
    "Russia_Taman": {
        "key": "Russia_Taman",
        "name": "Port of Taman (Black Sea Bulk Terminal)",
        "country": "Russia",
        "region": "Black Sea",
        "maxDraft": 18.0,
        "maxLOA": 300,
        "allowedClasses": ["Capesize", "Kamsarmax", "Panamax", "Supramax"],
        "dailyLoadingRate": 60000,
        "portTariffPerTon": 3.20,
        "primaryCommodity": "Kuzbass Thermal & Anthracite Coal, PCI",
        "fobBenchmarkPriceUSD": 88.00,
        "caloricValueKcal": 5900,
        "chokepoints": ["Bosphorus Strait / Suez Canal / Bab-el-Mandeb"]
    },
    "Russia_UstLuga": {
        "key": "Russia_UstLuga",
        "name": "Port of Ust-Luga (Baltic Sea Terminal)",
        "country": "Russia",
        "region": "Baltic Sea",
        "maxDraft": 16.0,
        "maxLOA": 280,
        "allowedClasses": ["Capesize", "Panamax", "Supramax"],
        "dailyLoadingRate": 50000,
        "portTariffPerTon": 3.40,
        "primaryCommodity": "Thermal Coal, Petcoke, Fertilizer",
        "fobBenchmarkPriceUSD": 82.00,
        "caloricValueKcal": 5800,
        "chokepoints": ["Danish Straits / English Channel / Cape or Suez"]
    }
}

NAUTICAL_DISTANCES = {
    "Indonesia_Samarinda-Paradip": 2520,
    "Indonesia_Samarinda-Vizag": 2440,
    "Indonesia_Samarinda-Gangavaram": 2430,
    "Indonesia_Samarinda-Gopalpur": 2480,
    "Indonesia_Samarinda-Dhamra": 2550,
    "Indonesia_Samarinda-SagarSandheads": 2580,
    "Indonesia_Samarinda-Haldia": 2640,

    "Indonesia_Taboneo-Paradip": 2380,
    "Indonesia_Taboneo-Vizag": 2300,
    "Indonesia_Taboneo-Gangavaram": 2290,
    "Indonesia_Taboneo-Gopalpur": 2340,
    "Indonesia_Taboneo-Dhamra": 2410,
    "Indonesia_Taboneo-SagarSandheads": 2440,
    "Indonesia_Taboneo-Haldia": 2500,

    "Australia_Newcastle-Paradip": 5100,
    "Australia_Newcastle-Vizag": 4980,
    "Australia_Newcastle-Gangavaram": 4970,
    "Australia_Newcastle-Gopalpur": 5040,
    "Australia_Newcastle-Dhamra": 5140,
    "Australia_Newcastle-SagarSandheads": 5180,
    "Australia_Newcastle-Haldia": 5230,

    "Australia_HayPoint-Paradip": 4680,
    "Australia_HayPoint-Vizag": 4560,
    "Australia_HayPoint-Gangavaram": 4550,
    "Australia_HayPoint-Gopalpur": 4620,
    "Australia_HayPoint-Dhamra": 4710,
    "Australia_HayPoint-SagarSandheads": 4750,
    "Australia_HayPoint-Haldia": 4800,

    "Mozambique_Maputo-Paradip": 4380,
    "Mozambique_Maputo-Vizag": 4240,
    "Mozambique_Maputo-Gangavaram": 4230,
    "Mozambique_Maputo-Gopalpur": 4310,
    "Mozambique_Maputo-Dhamra": 4410,
    "Mozambique_Maputo-SagarSandheads": 4450,
    "Mozambique_Maputo-Haldia": 4500,

    "Mozambique_Nacala-Paradip": 3650,
    "Mozambique_Nacala-Vizag": 3510,
    "Mozambique_Nacala-Gangavaram": 3500,
    "Mozambique_Nacala-Gopalpur": 3580,
    "Mozambique_Nacala-Dhamra": 3680,
    "Mozambique_Nacala-SagarSandheads": 3720,
    "Mozambique_Nacala-Haldia": 3770,

    "US_Norfolk-Paradip": 11150,
    "US_Norfolk-Vizag": 11020,
    "US_Norfolk-Gangavaram": 11010,
    "US_Norfolk-Gopalpur": 11090,
    "US_Norfolk-Dhamra": 11180,
    "US_Norfolk-SagarSandheads": 11220,
    "US_Norfolk-Haldia": 11280,

    "Russia_Taman-Paradip": 5480,
    "Russia_Taman-Vizag": 5340,
    "Russia_Taman-Gangavaram": 5330,
    "Russia_Taman-Gopalpur": 5410,
    "Russia_Taman-Dhamra": 5510,
    "Russia_Taman-SagarSandheads": 5550,
    "Russia_Taman-Haldia": 5600,

    "Russia_UstLuga-Paradip": 8550,
    "Russia_UstLuga-Vizag": 8410,
    "Russia_UstLuga-Gangavaram": 8400,
    "Russia_UstLuga-Gopalpur": 8480,
    "Russia_UstLuga-Dhamra": 8580,
    "Russia_UstLuga-SagarSandheads": 8620,
    "Russia_UstLuga-Haldia": 8680
}

CANDIDATE_VESSELS = [
    {
        "id": "VESSEL-01",
        "name": "MV Samarinda Express",
        "vesselClass": "Capesize",
        "dwt": 178000,
        "draft": 17.2,
        "loa": 292,
        "beam": 45.0,
        "speedKnots": 13.5,
        "bunkerConsumptionTonsPerDay": 42,
        "currentLocation": "Malacca Strait (Eastbound to Bay of Bengal)",
        "availableFromDay": 3,
        "dailyCharterRateMultiplier": 1.15,
        "ciiBaseRating": "A",
        "co2GramsPerTonNM": 3.65
    },
    {
        "id": "VESSEL-02",
        "name": "MV Bharat Glory",
        "vesselClass": "Kamsarmax",
        "dwt": 82000,
        "draft": 14.2,
        "loa": 229,
        "beam": 32.3,
        "speedKnots": 14.0,
        "bunkerConsumptionTonsPerDay": 27,
        "currentLocation": "Bay of Bengal (Off Paradip Anchorage)",
        "availableFromDay": 1,
        "dailyCharterRateMultiplier": 0.95,
        "ciiBaseRating": "B",
        "co2GramsPerTonNM": 4.85
    },
    {
        "id": "VESSEL-03",
        "name": "MV Ocean Sentinel",
        "vesselClass": "Panamax",
        "dwt": 76000,
        "draft": 13.8,
        "loa": 225,
        "beam": 32.2,
        "speedKnots": 13.2,
        "bunkerConsumptionTonsPerDay": 25,
        "currentLocation": "Singapore Anchorage (Repositioning)",
        "availableFromDay": 4,
        "dailyCharterRateMultiplier": 0.90,
        "ciiBaseRating": "C",
        "co2GramsPerTonNM": 5.60
    },
    {
        "id": "VESSEL-04",
        "name": "MV Ganga Titan",
        "vesselClass": "Capesize",
        "dwt": 180000,
        "draft": 17.8,
        "loa": 295,
        "beam": 45.5,
        "speedKnots": 13.0,
        "bunkerConsumptionTonsPerDay": 45,
        "currentLocation": "Indian Ocean (Off Sri Lanka)",
        "availableFromDay": 5,
        "dailyCharterRateMultiplier": 1.18,
        "ciiBaseRating": "A",
        "co2GramsPerTonNM": 3.75
    },
    {
        "id": "VESSEL-05",
        "name": "MV Bengal Pioneer",
        "vesselClass": "Supramax",
        "dwt": 58000,
        "draft": 8.4,
        "loa": 188,
        "beam": 31.0,
        "speedKnots": 12.8,
        "bunkerConsumptionTonsPerDay": 20,
        "currentLocation": "Sandheads Pilot Boarding Grounds",
        "availableFromDay": 1,
        "dailyCharterRateMultiplier": 0.78,
        "ciiBaseRating": "D",
        "co2GramsPerTonNM": 7.20
    },
    {
        "id": "VESSEL-06",
        "name": "MV Kalinga Voyager",
        "vesselClass": "Ultramax",
        "dwt": 64000,
        "draft": 12.8,
        "loa": 199,
        "beam": 32.2,
        "speedKnots": 13.4,
        "bunkerConsumptionTonsPerDay": 22,
        "currentLocation": "Off Vizag Outer Anchorage",
        "availableFromDay": 2,
        "dailyCharterRateMultiplier": 0.84,
        "ciiBaseRating": "B",
        "co2GramsPerTonNM": 5.10
    }
]

def get_nautical_distance(origin_key: str, dest_key: str) -> int:
    lookup = f"{origin_key}-{dest_key}"
    if lookup in NAUTICAL_DISTANCES:
        return NAUTICAL_DISTANCES[lookup]
    if "Indonesia" in origin_key: return 2500
    if "Australia" in origin_key: return 4900
    if "Mozambique" in origin_key: return 4000
    if "Russia" in origin_key: return 5800
    if "US" in origin_key: return 11000
    return 3500

